create extension if not exists pgcrypto;

create table if not exists public.access_logs (
  id bigint generated by default as identity primary key,
  session_id text not null,
  path text not null,
  title text,
  referrer text,
  language text,
  screen_width integer,
  screen_height integer,
  user_agent text,
  ip_hash text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  event_name text not null,
  path text,
  category text,
  label text,
  value numeric,
  metadata_json jsonb,
  user_agent text,
  ip_hash text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  session_id text not null,
  name text not null,
  email text not null,
  company text not null,
  message text not null,
  source_path text not null,
  user_agent text,
  ip_hash text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_access_logs_created_at on public.access_logs (created_at desc);
create index if not exists idx_access_logs_session_id on public.access_logs (session_id);
create index if not exists idx_events_created_at on public.events (created_at desc);
create index if not exists idx_events_event_name on public.events (event_name);
create index if not exists idx_events_session_id on public.events (session_id);
create index if not exists idx_contact_submissions_created_at on public.contact_submissions (created_at desc);
create index if not exists idx_contact_submissions_session_id on public.contact_submissions (session_id);

alter table public.access_logs enable row level security;
alter table public.events enable row level security;
alter table public.contact_submissions enable row level security;
